version: '2'

networks:
  default:

services:

  orderer.samtest.com: 
    image: hyperledger/fabric-orderer:x86_64-1.0.5
    container_name: orderer.samtest.org
    environment: 
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISPROFILE=SamTest
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=samtest.com
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - CORE_PEER_ADDRESSAUTODETECT=true

    working_dir: /home/hyperledger/go/src/PlatoonTest
    command: orderer
    volumes: 
      - ./artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/samtest.com/orderers/orderer.samtest.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/samtest.com/orderers/orderer.samtest.com/tls:/var/hyperledger/orderer/tls
      - ./crypto-config/ordererOrganizations/samtest.com/orderers/orderer.samtest.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7050:7050
    networks:
      default:
        aliases:
          - orderer.samtest.com

  ca.org1.samtest.com:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    container_name: ca.org1.samtest.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.samtest.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.samtest.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3bdd03da0a728c40e1b0a85f7dac14d816202f21f4cddb202c8daa8d99e6c508_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.samtest.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3bdd03da0a728c40e1b0a85f7dac14d816202f21f4cddb202c8daa8d99e6c508_sk
      - CORE_PEER_ADDRESSAUTODETECT=true
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    working_dir: /home/hyperledger/go/src/PlatoonTest
    volumes:
      - ./crypto-config/peerOrganizations/org1.samtest.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.org1.samtest.com

  peer0.org1.samtest.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer0.org1.samtest.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=samtest
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.samtest.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org1.samtest.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.samtest.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.samtest.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.samtest.com
    working_dir: /home/hyperledger/go/src/PlatoonTest
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.samtest.com/peers/peer0.org1.samtest.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.samtest.com/peers/peer0.org1.samtest.com/tls:/var/hyperledger/tls
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.samtest.com
    links:
      - orderer.samtest.com
    networks:
      default:
        aliases:
          - peer0.org1.samtest.com

  peer1.org1.samtest.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer1.org1.samtest.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=samtest
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.samtest.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org1.samtest.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.samtest.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.samtest.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.org1.samtest.com
    working_dir: /home/hyperledger/go/src/PlatoonTest
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.samtest.com/peers/peer1.org1.samtest.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.samtest.com/peers/peer1.org1.samtest.com/tls:/var/hyperledger/tls
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.samtest.com
    links:
      - orderer.samtest.com
    networks:
        default:
          aliases:
            - peer1.org1.samtest.com
